name: build image

on:
  push:
    tags:
    - 'v[0-9].[0-9]+.[0-9]+*'

env:
  IMAGE_REPO: registry.cn-beijing.aliyuncs.com/llaoj/fluent-bit-clickhouse

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          echo "image=${IMAGE_REPO}:${GIT_TAG}" >> $GITHUB_ENV

      - name: Build and push image to ACR
        run: |
          docker build -t ${{ env.image }} .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ env.image }}
          docker push ${{ env.image }}